let state={history:[],missed:[]};let storageAvailable=true;
try{const saved=JSON.parse(localStorage.getItem('cleared-v1')||'null');if(saved&&Array.isArray(saved.history)&&Array.isArray(saved.missed)){state.history=saved.history;state.missed=saved.missed.filter(id=>questions.some(q=>q.id===id));}}catch{storageAvailable=false;}
let session=null;let currentView='dashboard';
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('cleared-v1',JSON.stringify(state));}catch{storageAvailable=false;}document.getElementById('nav-count').textContent=state.missed.length;}
function heading(title,subtitle){return `<div class="page-head"><div><div class="eyebrow">YOUR CHECKRIDE STARTS HERE</div><h1>${title}</h1><p>${subtitle}</p></div><span class="badge">✦ Private Pilot · Airplane</span></div>${!storageAvailable?'<p role="alert">Device storage is unavailable. Progress will last only for this visit.</p>':''}`;}
function chart(){const runs=state.history.slice(-8);return runs.length?`<div class="chart" aria-label="Recent quiz scores">${runs.map(r=>`<div class="bar-wrap"><div class="bar" style="height:${r.score}%"><span>${r.score}%</span></div><small>${new Date(r.date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></div>`).join('')}</div>`:'<div class="empty">Your flight path starts with your first quiz.<br>Finish a session to see your scores here.</div>';}
function topicCards(all=false){return `<div class="topics">${(all?topics:topics.slice(0,6)).map(t=>{const count=questions.filter(q=>q.topic===t.id).length;return `<article class="card topic"><div class="icon">${t.icon}</div><span class="topic-number">AREA ${t.roman}</span><h3>${t.name}</h3><p>${t.description}</p><div class="topic-bottom"><span>${count} questions · ACS area ${t.roman}</span><button data-quiz="${t.id}">Study topic ↗</button></div></article>`;}).join('')}</div>`;}
function show(view){currentView=view;session=null;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));save();
 if(view==='dashboard'){const total=state.history.reduce((s,r)=>s+r.total,0);const correct=state.history.reduce((s,r)=>s+r.correct,0);app.innerHTML=heading('A little study. A lot more confidence.','Stay sharp, close the gaps, and get ready for your private pilot checkride.')+`<section class="hero"><div><div class="eyebrow">READY FOR YOUR NEXT SESSION?</div><h2>Great pilots never<br>stop learning.</h2><p>Turn a few spare minutes into checkride confidence. Practice across the ACS, one question at a time.</p><button class="primary" data-quiz="mixed">Start a quick quiz ↗</button></div><div class="flight-art" aria-hidden="true"><div class="orbit"></div><div class="plane">✈</div><div class="art-label">KNOWLEDGE → CONFIDENCE → FLIGHT</div></div></section><div class="stats"><div class="stat"><span class="label">Overall accuracy</span><strong>${total?Math.round(correct/total*100)+'%':'—'}</strong><small>Across completed sessions</small></div><div class="stat"><span class="label">Questions answered</span><strong>${total}</strong><small>Every rep moves you forward</small></div><div class="stat"><span class="label">To revisit</span><strong>${state.missed.length}</strong><small>Your personal review queue</small></div><div class="stat"><span class="label">Quizzes completed</span><strong>${state.history.length}</strong><small>Keep building consistency</small></div></div><div class="section-head"><h2>Study by ACS topic</h2><button class="text-button" data-view="topics">View all 11 topics →</button></div>${topicCards()}<div class="lower"><section class="card"><div class="section-head" style="margin-top:0"><h2>Your progress</h2><button class="text-button" data-view="progress">View history →</button></div><p>Small sessions. Steady improvement.</p>${chart()}</section><section class="card review-callout"><div class="eyebrow">MAKE IT STICK</div><h3>Turn missed questions<br>into your strengths.</h3><p>Your review queue collects the questions that need another look. Answer them correctly to clear them.</p><button class="secondary" data-view="review">Review missed questions →</button></section></div>`;}
 if(view==='topics')app.innerHTML=heading('Explore your study topics.','Choose an ACS area, or practice a mix of topics.')+`<div class="section-head"><h2>11 areas. One confident pilot.</h2><button class="primary" data-quiz="mixed">Mixed quiz ↗</button></div>${topicCards(true)}<p style="font-size:12px">Starter question bank: ${questions.length} original practice questions mapped to ACS areas. This is not exhaustive ACS task coverage. Verify current requirements with the FAA Private Pilot Airplane ACS, regulations, and your aircraft POH/AFM.</p>`;
 if(view==='review'){const missed=questions.filter(q=>state.missed.includes(q.id));app.innerHTML=heading('Close the gaps.','Questions you miss stay here until you answer them correctly.')+`<div class="section-head"><h2>${missed.length} questions to revisit</h2>${missed.length?'<button class="primary" data-quiz="review">Start review ↗</button>':''}</div>`+(missed.length?missed.map(q=>`<article class="card missed-row"><span class="pill">${topics.find(t=>t.id===q.topic).name}</span><h3>${esc(q.prompt)}</h3><p>Practice this question in a review session to clear it from your queue.</p></article>`).join(''):'<section class="card empty">All clear. Missed questions will appear here after you practice.<br><br><button class="primary" data-quiz="mixed">Start a quiz ↗</button></section>');}
 if(view==='progress')app.innerHTML=heading('See how far you’ve come.','Your completed sessions, saved on this browser and device.')+`<section class="card"><h2>Recent scores</h2>${chart()}</section><div class="section-head"><h2>Session history</h2><button class="text-button" id="reset">Reset progress</button></div><section class="card">${state.history.length?state.history.slice().reverse().map(r=>`<div class="history-row"><div>${esc(r.label)}<small>${new Date(r.date).toLocaleString()}</small></div><div><b>${r.score}%</b><small>${r.correct} of ${r.total} correct</small></div></div>`).join(''):'<div class="empty">No completed sessions yet. Take a quiz to record your first score.</div>'}</section>`;
 if(view==='atc')app.innerHTML=atcPrep();
 if(view==='radio')renderRadio();
 if(view==='training')app.innerHTML=trainingPage();
 if(view==='weather')app.innerHTML=weatherPage();
 window.scrollTo({top:0,behavior:'smooth'});
}
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function start(id){const pool=questions.filter(q=>id==='mixed'||(id==='review'?state.missed.includes(q.id):q.topic===id));if(!pool.length)return show('review');session={items:shuffle(pool).slice(0,id==='mixed'?10:pool.length),index:0,correct:0,selected:null,label:id==='mixed'?'Mixed ACS quiz':id==='review'?'Missed-question review':topics.find(t=>t.id===id).name};renderQuestion();}
function renderQuestion(){const q=session.items[session.index];app.innerHTML=`<section class="quiz"><button class="text-button" id="exit">← End session</button><div class="quiz-meta"><span>${esc(session.label)}</span><span>Question ${session.index+1} of ${session.items.length}</span></div><div class="track"><span style="width:${session.index/session.items.length*100}%"></span></div><span class="pill">ACS ${topics.find(t=>t.id===q.topic).roman} · ${topics.find(t=>t.id===q.topic).name}</span><h2>${esc(q.prompt)}</h2><div class="answers">${q.options.map((a,i)=>`<button class="answer" data-answer="${i}"><span class="letter">${String.fromCharCode(65+i)}</span>${esc(a)}</button>`).join('')}</div><div id="feedback" aria-live="polite"></div><p style="font-size:11px">Choose an answer to see the explanation and reference.</p></section>`;window.scrollTo({top:0});}
function answer(index){if(!session||session.selected!==null)return;session.selected=index;const q=session.items[session.index];const correct=index===q.answer;if(correct){session.correct++;state.missed=state.missed.filter(id=>id!==q.id);}else if(!state.missed.includes(q.id))state.missed.push(q.id);save();document.querySelectorAll('.answer').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');else if(i===index)b.classList.add('wrong');});document.getElementById('feedback').innerHTML=`<div class="feedback"><b>${correct?'✓ Correct. Nicely done.':'Let’s take another look.'}</b><p>${esc(q.explanation)}</p><p><small>Reference: ${esc(q.source)}</small></p></div><div class="quiz-actions"><span>${session.correct} correct so far</span><button class="primary" id="next">${session.index+1===session.items.length?'See results':'Next question'} →</button></div>`;}
function next(){if(session.selected===null)return;session.index++;session.selected=null;if(session.index<session.items.length)return renderQuestion();const r={date:new Date().toISOString(),label:session.label,total:session.items.length,correct:session.correct,score:Math.round(session.correct/session.items.length*100)};state.history.push(r);save();session=null;app.innerHTML=`<section class="quiz card result"><div class="eyebrow">SESSION COMPLETE</div><h1>Another step toward cleared.</h1><strong>${r.score}%</strong><p>${r.correct} of ${r.total} questions correct.<br>${state.missed.length?'Your missed questions are ready for another look.':'Your review queue is clear. Keep the momentum going.'}</p><button class="primary" data-view="review">Review missed questions</button><button class="secondary" data-view="dashboard">Back to dashboard</button></section>`;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){if(session&&!confirm('End this quiz? Your answered questions stay in the review queue, but this incomplete session will not record a score.'))return;show(b.dataset.view);}if(b.dataset.quiz)start(b.dataset.quiz);if(b.dataset.answer!==undefined)answer(Number(b.dataset.answer));if(b.id==='next')next();if(b.id==='exit'&&confirm('End this quiz? No score will be recorded for this incomplete session.'))show(currentView);if(b.id==='reset'&&confirm('Delete all quiz history and missed questions on this device?')){state={history:[],missed:[]};save();show('progress');}});
show('dashboard');
