const topics = [
 ['preflight','I','Preflight preparation','The decisions that make a safe flight.','◎'],
 ['procedures','II','Preflight procedures','Know your aircraft before you take off.','☑'],
 ['airport','III','Airport operations','Clear communication. Confident operations.','↗'],
 ['takeoff','IV','Takeoffs, landings & go-arounds','Build a solid foundation for every flight.','⇗'],
 ['performance','V','Performance & ground reference','Precision, coordination, and control.','⌁'],
 ['navigation','VI','Navigation','Find your way, and stay ahead of the airplane.','⌖'],
 ['slow','VII','Slow flight & stalls','Recognize limits. Maintain control.','◴'],
 ['basic','VIII','Basic instrument maneuvers','Trust the instruments when visibility fades.','◉'],
 ['emergency','IX','Emergency operations','Prepare for the unexpected.','⚡'],
 ['night','X','Night operations','A different perspective after sunset.','☾'],
 ['postflight','XI','Postflight procedures','Finish every flight with care.','✓']
].map(([id,roman,name,description,icon])=>({id,roman,name,description,icon}));
const rawQuestions = [
 ['preflight','Before acting as PIC, what must a pilot become familiar with?',['All available information concerning that flight','Only the destination weather','Only the aircraft fuel quantity'],0,'14 CFR 91.103 requires all available information, including weather, fuel requirements, alternatives, and applicable runway and performance information.','14 CFR 91.103'],
 ['preflight','What is the minimum fuel reserve for a daytime VFR airplane flight?',['20 minutes at cruise','30 minutes at normal cruising speed','45 minutes at normal cruising speed'],1,'Plan enough fuel to reach the first intended landing point and then fly at normal cruising speed for at least 30 minutes by day (45 minutes at night).','14 CFR 91.151'],
 ['preflight','In Class E airspace below 10,000 feet MSL, what are the basic VFR weather minimums?',['1 mile and clear of clouds','3 miles, 500 feet below, 1,000 feet above, 2,000 feet horizontal','5 miles and 1,000 feet in every direction'],1,'The usual Class E minimums below 10,000 feet MSL are 3 statute miles and the 500/1,000/2,000 cloud clearances.','14 CFR 91.155'],
 ['preflight','A high density altitude generally causes what effect?',['Shorter takeoff distance','Reduced aircraft performance and longer takeoff distance','More engine power'],1,'Hot temperatures, high elevation, and reduced air density decrease engine, propeller, and wing performance. Use your aircraft performance charts.','FAA PHAK, Aircraft Performance'],
 ['procedures','Who determines that an aircraft is in condition for safe flight?',['The pilot in command','Only the last mechanic','The airport manager'],0,'The PIC is responsible for determining whether the aircraft is in condition for safe flight and must discontinue flight when unairworthy conditions occur.','14 CFR 91.7'],
 ['procedures','During an engine run-up, a check falls outside the POH limits. What is the best action?',['Depart if the engine sounds normal','Investigate and resolve the discrepancy before flight','Use extra takeoff power'],1,'Follow the aircraft checklist and limitations. An out-of-limit indication requires diagnosis before departure.','FAA Airplane Flying Handbook, Ground Operations'],
 ['airport','At a towered airport, when is a runway crossing permitted?',['Whenever no traffic is visible','Only after receiving the required explicit crossing clearance','When cleared to taxi to any runway'],1,'A taxi clearance does not automatically authorize crossing a runway. Obtain an explicit clearance for each runway crossing and read back the runway assignment.','FAA AIM, Taxiing'],
 ['airport','What does a steady red light signal mean to an aircraft in flight?',['Cleared to land','Give way to other aircraft and continue circling','Airport unsafe, do not land'],1,'For an aircraft in flight, steady red means give way to other aircraft and continue circling. Flashing red means airport unsafe, do not land.','FAA AIM, Light Gun Signals'],
 ['takeoff','When should a pilot initiate a go-around?',['Only after touching down','Whenever a safe landing is in doubt','Only when directed by the tower'],1,'An unstable approach, runway conflict, or other uncertainty about a safe landing warrants a timely go-around using the aircraft procedure.','FAA Airplane Flying Handbook, Approaches and Landings'],
 ['takeoff','For a short-field takeoff, where should the pilot obtain speeds and configuration?',['A generic internet checklist','The aircraft POH/AFM','The previous aircraft flown'],1,'Use aircraft-specific procedures, configuration, and performance data from the POH/AFM.','FAA Airplane Flying Handbook, Takeoffs'],
 ['performance','In a coordinated level turn, increasing bank angle has what effect?',['It increases load factor and stall speed','It decreases stall speed','It has no effect on load factor'],0,'Maintaining altitude in a steeper bank requires greater lift, increasing load factor. Stall speed rises with the square root of load factor.','FAA PHAK, Aerodynamics of Flight'],
 ['performance','In a ground reference maneuver, where is the steepest bank generally needed?',['On the downwind portion','On the upwind portion','At every point equally'],0,'Higher groundspeed on the downwind portion requires a higher rate of turn and steeper bank to maintain a constant ground radius.','FAA Airplane Flying Handbook, Ground Reference Maneuvers'],
 ['navigation','A wind from the right of the intended course requires what correction?',['Turn left of course','Point the nose right of course','Reduce altitude'],1,'Crab into the wind to offset drift; the heading is to the right of the desired ground track when wind comes from the right.','FAA PHAK, Navigation'],
 ['navigation','If you become lost, which is an appropriate action?',['Continue until fuel is nearly exhausted','Maintain control, use navigation resources, and seek ATC assistance early','Descend immediately without checking terrain'],1,'Maintain aircraft control, assess fuel and terrain, use available navigation tools, and communicate early. Climb only if safe and appropriate.','FAA Airplane Flying Handbook, Emergency Procedures'],
 ['slow','What causes an aerodynamic stall?',['Exceeding the critical angle of attack','Flying below one fixed airspeed in all conditions','An engine failure'],0,'A wing stalls when it exceeds its critical angle of attack, at any airspeed, attitude, or power setting.','FAA PHAK, Aerodynamics of Flight'],
 ['slow','What is the essential first aerodynamic action for stall recovery?',['Increase angle of attack','Reduce angle of attack','Apply full rudder'],1,'Reduce angle of attack below the critical angle, then use the aircraft-specific recovery procedure and appropriate power.','FAA Airplane Flying Handbook, Stalls'],
 ['basic','In an inadvertent encounter with IMC, what is a key immediate priority?',['Maintain control using the flight instruments','Make a steep visual turn','Look outside exclusively'],0,'Control the airplane using the instruments, avoid abrupt maneuvers, and obtain assistance. Prevention through sound weather decisions remains essential.','FAA Airplane Flying Handbook, Emergency Procedures'],
 ['basic','Which instrument directly displays pitch and bank attitude?',['Altimeter','Attitude indicator','Airspeed indicator'],1,'The attitude indicator displays pitch and bank relative to the horizon. Cross-check other instruments to verify performance.','FAA PHAK, Flight Instruments'],
 ['emergency','After an engine failure, what is the immediate priority?',['Troubleshoot before adjusting airspeed','Maintain aircraft control and establish an appropriate glide','Make a radio call before flying the airplane'],1,'Aviate first: establish the POH-recommended glide speed, select a landing area, then perform checks and communicate as time permits.','FAA Airplane Flying Handbook, Emergency Procedures'],
 ['emergency','What does squawking 7700 indicate?',['A general emergency','Radio failure only','Unlawful interference only'],0,'7700 is the general emergency code. 7600 indicates communications failure; 7500 indicates unlawful interference.','FAA AIM, Emergency Services'],
 ['night','What is the minimum fuel reserve for a VFR airplane flight at night?',['20 minutes','30 minutes','45 minutes at normal cruising speed'],2,'For VFR at night, carry enough fuel to reach the first intended landing point and fly for at least 45 minutes at normal cruising speed.','14 CFR 91.151'],
 ['night','How can a pilot help preserve night vision?',['Avoid bright lights and allow time for dark adaptation','Stare at bright cockpit lights','Use maximum lighting continuously'],0,'Dark adaptation takes time. Keep lighting at a useful low level while ensuring instruments and charts remain readable.','FAA PHAK, Aeromedical Factors'],
 ['postflight','What is a good postflight action when a new discrepancy is found?',['Leave it for the next pilot to discover','Record and report it using the aircraft/operator procedure','Ignore it if the flight was completed'],1,'Document and communicate discrepancies so airworthiness can be evaluated before the next flight.','FAA Airplane Flying Handbook, Postflight'],
 ['postflight','Why secure the aircraft using the recommended checklist?',['To protect it from movement and weather and leave it safely configured','Only to improve its appearance','To eliminate future preflight inspections'],0,'Proper parking, shutdown, control locks, and tiedowns or chocks protect the aircraft. Follow aircraft and airport procedures.','FAA Airplane Flying Handbook, Ground Operations']
];
const questions=rawQuestions.map(([topic,prompt,options,answer,explanation,source],i)=>({id:'q'+i,topic,prompt,options,answer,explanation,source}));
if(typeof module!=='undefined') module.exports={topics,questions};
